#pragma once

#include "../../include/libc/errno.h"

#define BZ_ERR_MATH_DOMAIN      EDOM
#define BZ_ERR_ILLEGAL_SEQUENCE EILSEQ
#define BZ_ERR_OUT_OF_RANGE     ERANGE
#define BZ_ERR_NOT_PERMITTED    EPERM
#define BZ_ERR_FILE_NOT_FOUND   ENOENT
#define BZ_ERR_BAD_FD           EBADF
#define BZ_ERR_OUT_OF_MEMORY    ENOMEM
#define BZ_ERR_ACCESS_DENIED    EACCES
#define BZ_ERR_FILE_EXISTS      EEXIST
#define BZ_ERR_NOT_A_DIRECTORY  ENOTDIR
#define BZ_ERR_IS_A_DIRECTORY   EISDIR
#define BZ_ERR_INVALID_ARGUMENT EINVAL
#define BZ_ERR_TOO_MANY_FDS     EMFILE
#define BZ_ERR_NO_SPACE         ENOSPC
#define BZ_ERR_NOT_SEEKABLE     ESPIPE
#define BZ_ERR_NOT_IMPLEMENTED  ENOSYS
